remove stboot
u-root/u-root pull request #2003
Opened 2021-05-12 14:26 UTC by jensdrenhaus

The stboot code in master branch is outdated. Recent changes are at the
stboot branch.
The project is moved to https://github.com/system-transparency/stboot.
The stboot branch will remain here for some time.

Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>

2021-05-12 17:16 UTC, rminnich approved these changes

2021-05-12 17:17 UTC, rminnich approved these changes

2021-05-12 17:49 UTC, rminnich commented
could you squash these into one? We're trying to follow the rule that we be able to checkout out any commit and it will build.

2021-05-12 17:50 UTC, rminnich requested changes
Ii did not realize this would leave a broken commit in the tree as done; can you squash?

2021-05-12 17:55 UTC, jensdrenhaus commented
> Ii did not realize this would leave a broken commit in the tree as done; can you squash?

Sure. Done

2021-05-13 23:23 UTC, rminnich approved these changes

2021-05-13 23:23 UTC, merged