Create spi package for Linux spidev driver
u-root/u-root pull request #2060
Opened 2021-07-01 05:42 UTC by rjoleary

This package is fairly low-level. In follow-up packages, I will add a
"spi/flash" package with basic Read/Write operations for flash chips
based on this package.

Tested on a RPI3 with a SPI loopback.

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

2021-07-01 05:45 UTC, rjoleary commented
I went a little overboard with the unit tests, but they caught 2-3 hidden bugs, so they proved helpful.

2021-07-02 06:51 UTC, rjoleary commented
Here is a photo of the loopback used for testing:

![loopback](https://user-images.githubusercontent.com/2763535/124232936-250eb500-dac7-11eb-81e3-76094be6fef9.jpg)

2021-07-08 21:08 UTC, hugelgupf requested changes
didn't review the unit tests for now

2021-07-08 21:08 UTC, hugelgupf commented on pkg/spi/spidev_linux.go
> +			it[i].txBuf = uint64(uintptr(unsafe.Pointer(&transfers[i].Tx[0])))
see my comment about GC above

2021-07-08 21:08 UTC, hugelgupf commented on pkg/spi/spidev_linux.go
> +		return err
since this is just an errno, maybe wrap it in something nice? an os.SyscallError that adds some context, for example

2021-07-08 21:51 UTC, rjoleary commented on pkg/spi/spidev_linux.go
> +			return unix.Syscall(trap, a1, a2, uintptr(a3))
I might be wrong, but isn't this covered by the `unsafe` documentation:

```
If a pointer argument must be converted to uintptr for use as an argument, that conversion must appear in the call expression itself:

syscall.Syscall(SYS_READ, uintptr(fd), uintptr(unsafe.Pointer(p)), uintptr(n))

The compiler handles a Pointer converted to a uintptr in the argument list of a call to a function implemented in assembly by arranging that the referenced allocated object, if any, is retained and not moved until the call completes, even though from the types alone it would appear that the object is no longer needed during the call.
```

2021-07-08 21:59 UTC, rjoleary commented on pkg/spi/spidev_linux.go
> +	txBuf uint64
I have some doubts that `*byte` or `unsafe.Pointer` would work here. The tx_buf in the kernel is always a u64 (https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/include/uapi/linux/spi/spidev.h#L71) even on 32bit machines. For example, on the rpi, the kernel and userspace is 32bit, but txBuf is still 64bit. How does Go know to cast the 32bit `*byte` to a u64?

2021-07-08 22:06 UTC, rjoleary commented on pkg/spi/spidev_linux.go
> +			it[i].txBuf = uint64(uintptr(unsafe.Pointer(&transfers[i].Tx[0])))
See my response above. I think it would only work if the type of `txBuf` is `uint`. Since the type in the kernel is a fixed size, but the size of a pointer varies, we have to have to cast to `uint64`.

2021-07-08 22:31 UTC, rjoleary commented on pkg/spi/spidev_linux.go
> +	txBuf uint64
But regardless, I think we do need some KeepAlive for Tx and Rx.

2021-07-09 04:25 UTC, rjoleary commented on cmds/contrib/spidev/spidev.go
> +			Rx:       make([]byte, len(tx)),
My understanding is you're limited to the size of INT_MAX or how much memory is on your computer.

2021-07-09 04:31 UTC, rjoleary commented on pkg/spi/spidev_linux.go
> +	// the next transfer.
I added "Chip Select" to the description. I made some assumptions the user would already know about spi and skipped explaining the electrical and wiring details -- there a good resources such as https://en.wikipedia.org/wiki/Serial_Peripheral_Interface#Independent_slave_configuration

2021-07-09 04:32 UTC, rjoleary commented on pkg/spi/spidev_linux.go
> +	txBuf uint64
I added KeepAlive.

2021-07-09 21:38 UTC, chrisfenner reviewed
Not being an expert in SPI or unsafe, I mostly read through this code to try to learn a little bit more. I left a couple of extremely nitpicky comments. FWIW, this change looks good to my novice eyes.

2021-07-09 21:38 UTC, chrisfenner commented on cmds/contrib/spidev/spidev_test.go
> +// fakeSpidev togglers to ASCII case of each byte in the transfer.
"togglers to" -> "toggles the"?

2021-07-09 21:38 UTC, chrisfenner commented on cmds/contrib/spidev/spidev_test.go
> +		// This toggles the ASCII case. Don't think too hard about --
"about" -> "about it"?

2021-07-13 17:43 UTC, rjoleary commented
This really is waiting for review. All the comments have been addressed.

2021-07-14 23:31 UTC, hugelgupf commented on pkg/spi/spidev_linux.go
> +			return unix.Syscall(trap, a1, a2, uintptr(a3))
I can't say that I've observed that to be true in reality. I see that has been there since 2016, but we had problems not putting runtime.KeepAlive right [here](https://github.com/u-root/u-root/blob/ab819d854d080062caf6f195ec8dc231f03e4177/pkg/ipmi/ipmi.go#L209) (Prachi ran tests on this at scale, incidence of about 3-5/1000 had it garbage collected before use in the call)

Even the Go unix package uses runtime.KeepAlive everywhere for stuff like this, e.g. for ioctls [here](https://github.com/golang/sys/blob/93ed5bcd2bfe7230f8abd84e0663ab1cb9148722/unix/ioctl_linux.go#L37)

2021-07-15 03:58 UTC, rjoleary commented on pkg/spi/spidev_linux.go
> +			return unix.Syscall(trap, a1, a2, uintptr(a3))
That example in the unix package can be explained because the `ioctl` function isn't assembly. They guarantee `Syscall` is in assembly, so rule #4 from `go doc unsafe.Pointer` applies. You can see that calls directly to `Syscall` don't have a KeepAlive, for example [here](https://github.com/golang/sys/blob/93ed5bcd2bfe7230f8abd84e0663ab1cb9148722/unix/zsyscall_linux.go#L435).

2021-07-15 04:03 UTC, rjoleary commented on pkg/spi/spidev_linux.go
> +			return unix.Syscall(trap, a1, a2, uintptr(a3))
I suspect it may have also been the case for the ipmi package, it was once wrapped in a Ioctl function and changed in https://github.com/u-root/u-root/pull/1705/files, but the Ioctl function was removed at the same time KeepAlive was added, so it depends on when you made that observation.

2021-07-16 23:40 UTC, rminnich commented on pkg/spi/spidev_linux.go
> +			return unix.Syscall(trap, a1, a2, uintptr(a3))
Checked with Russ, he took a look, he feels is it not needed.

2021-07-16 23:41 UTC, rminnich approved these changes

2021-07-16 23:56 UTC, merged