GitHub actions update
u-root/u-root pull request #2662
Opened 2023-04-22 15:12 UTC by rminnich

2023-04-22 15:42 UTC, rminnich commented
The linter errors make no sense to me. Where is it getting pkg/bb?

2023-04-22 18:48 UTC, rminnich commented
Hi, while this is incomplete, I think we should bring it in, and iterate. This has been dragging for a very long time. Something that is partial is better than nothing. Thanks.

2023-04-23 04:58 UTC, rminnich commented
just fyi, the reason I want to get this in in this basic state is that part of the reason it broke was that u-root changed so much from when this PR was first submitted last july! This way, at least we can be sure it does not get broken again.

2023-04-23 05:59 UTC, binjip978 approved these changes
Looks like tests are failing by timeout in GitHub actions.

2023-04-23 17:42 UTC, hugelgupf requested changes
please do not merge until all the "echo FIX ME" are gone and stuff is running

2023-04-23 17:42 UTC, hugelgupf commented on uroot_test.go
> -		bbTest.env = append(bbTest.env, "GO111MODULE=off")
we still want to test this combination? please keep these tests

2023-04-23 17:42 UTC, hugelgupf commented on .github/workflows/ci.yml
> +      - name: Check every Template
This test has been deleted in the circleci workflow because it never ran. uroot_test.go is the place for this.

2023-04-23 17:43 UTC, hugelgupf commented on .github/workflows/ci.yml
> +        run: echo FIX ME go test -race -timeout=15m -failfast ./...
nothing actually running here

2023-04-23 17:43 UTC, hugelgupf commented on .github/workflows/ci.yml
> +        run: echo FIX ME go test -cover -coverprofile=coverage.txt -timeout=15m -failfast ./...
nothing actually running here

2023-04-23 17:43 UTC, hugelgupf commented on .github/workflows/go.yml
> +      run: echo not until it works golangci-lint run ./... --disable-all --enable=ineffassign
nothing running here -- why replace the old thing?

2023-04-23 18:48 UTC, rminnich commented
ok, gonna close this, at least it's an indicator of how it might move forward.

2023-04-23 18:48 UTC, closed without merging