Add LddAllowUnreachable
u-root/u-root pull request #2748
Opened 2023-08-25 08:49 UTC by ling2yt

2023-08-26 03:51 UTC, rminnich requested changes
There's a lot of things in here that don't compile. You will need to fix that first.

2023-08-26 03:51 UTC, rminnich commented on pkg/ldd/ldso_linux.go
> +	if os.Getenv("LD_LIB_PATH") != "" {
This name is wrong.

2023-08-29 18:41 UTC, ling2yt commented
create the pull request by mistake

2023-08-29 18:41 UTC, closed without merging

2023-08-29 18:45 UTC, ling2yt commented
> There's a lot of things in here that don't compile. You will need to fix that first.

Sorry I create the pull request by mistake. And what I want to confirm is whether we will support call the cross compile ldd to resolve the dependencies like find the arm execution dependencies on the x86 platform?