cmd/core/ip
u-root/u-root pull request #3015
Opened 2024-06-18 11:54 UTC by RiSKeD

# Todos
- [x] refactor parsing
- [ ] narrow down functionality
- [ ] implement missing feature set

2024-06-18 16:54 UTC, rminnich requested changes
I would prefer that you not make this change to parsing. 

The parsing has a very important goal: on error, the program should say exactly what it parsed successfully; what went wrong and why; and what was expected. 

While the current code could do this better, the current code is a HUGE improvement on the standard IP command, which is "dump an incorrect bnf on any error and ask the user to guess again". Further, the BNF that the ip command dumps is *wrong* -- the approach of the u-root IP command is nicer, because as the code changes, the error handling stays in sync. Further, you don't have to constantly see if there are enough args in argv -- if you panic due to running off the end of the array, it's ok, because the code is using panic in the parsing.

It may seem odd to use panic at all, given the general Go principle: "don't panic"
But rules are not absolute. I got the idea for using panic, as done here, from talks Rob Pike gave. I talked to Russ in 2018 about this usage of panic, and his comment is: "I still think it [panic] makes sense in a parser ..." with the caveat that it should not cross package boundaries. That rule is followed here (since it's all in main :-) and in the forth parser. Panic can make code a lot simpler.

Again, let's stick to extending the command, but I really don't want to see this parser rewrite.

2024-06-19 06:33 UTC, RiSKeD commented
The panics motivated me to rewrite it, but I understand that the old parsing is better from a user perspective.

2024-07-04 21:15 UTC, 10000TB commented
@RiSKeD should we make this ready for review ?

2024-07-04 21:15 UTC, 10000TB reviewed
left comments

2024-07-09 09:33 UTC, RiSKeD commented
> @RiSKeD should we make this ready for review ?

Not yet, I am iterating over all the subcommands which can be integrated with https://github.com/vishvananda/netlink/tree/main at the moment. After that, we can start the review process and look into what else should be prioritized in implementation.

2024-07-09 09:39 UTC, RiSKeD commented on cmds/core/ip/address_linux.go
> +		return fmt.Errorf(" subcommand %s not yet implemented, expected: %v", c, whatIWant)
Good call, i will check the parsing for each command again later on.

2024-07-24 06:59 UTC, RiSKeD commented on cmds/core/ip/parsing_linux.go
> +// The BNF it shows is not right in that case.
fixed

2024-07-26 16:13 UTC, rminnich reviewed
This is really impressive. Nice tests. I'm a bit overwhelmed at the size of it all, but it seems like an improvement ...
And you're not printing a BNF on error :)

2024-07-30 14:55 UTC, RiSKeD commented
I know this is a lot. I've refactored the parsing into some convenient helper functions, these are used all over the sub-commands. For now, this PR has exhausted all the current Netlink library's functionalities to my knowledge.

2024-07-30 16:26 UTC, rminnich reviewed
at some point, the old and the new commands got broken
./ip.risked link set
2024/07/30 09:22:45 ip: args: [./ip.risked link set], I got to arg 0, expected [] after that

we know it did not expect [] after that.
standard command says this: 
ip link set
Not enough information: "dev" argument is required.
(which is a real improvement: it no longer dumps the bnf either)

but the standard command behavior is terrible:
 ip link set dev
Command line is not complete. Try option "help"
it should show me the possibilities.

this branch shows
./ip.risked link set dev
2024/07/30 09:25:31 ip: args: [./ip.risked link set dev], I got to arg 0, expected [] after that
which is definitely wrong; it should show a slice of strings of network interfaces.

This is a lot closer but still not quite what we want.

2024-07-31 07:29 UTC, RiSKeD commented
> at some point, the old and the new commands got broken ./ip.risked link set 2024/07/30 09:22:45 ip: args: [./ip.risked link set], I got to arg 0, expected [] after that
> 
> we know it did not expect [] after that. standard command says this: ip link set Not enough information: "dev" argument is required. (which is a real improvement: it no longer dumps the bnf either)
> 
> but the standard command behavior is terrible: ip link set dev Command line is not complete. Try option "help" it should show me the possibilities.
> 
> this branch shows ./ip.risked link set dev 2024/07/30 09:25:31 ip: args: [./ip.risked link set dev], I got to arg 0, expected [] after that which is definitely wrong; it should show a slice of strings of network interfaces.
> 
> This is a lot closer but still not quite what we want.

Something went wrong when I refactored the globals into the cmd struct and forgot to use Pointer receiver funcs instead of value-based funcs. I'll push a commit with a fix

2024-07-31 21:01 UTC, rminnich commented
will test when I get home. thanks.

2024-08-01 05:57 UTC, rminnich approved these changes

2024-08-01 05:58 UTC, merged