pkg/boot/universalpayload: Refine FDT node info; refine assembly code and skip reporting PCI ROOT bridge resource region
u-root/u-root pull request #3256
Opened 2024-12-26 13:00 UTC by AjanZhong

2025-01-01 21:46 UTC, rminnich approved these changes

2025-01-01 21:46 UTC, rminnich approved these changes

2025-01-06 10:47 UTC, leongross commented
Just as a reminder, since I am currently working on the tiyngo support; the current changes you proposed will only affect the non-tinygo builds, since you did not adjust the cgo implementations in [trampoline_tinygo_amd64.h](https://github.com/u-root/u-root/blob/main/pkg/boot/universalpayload/trampoline_tinygo_amd64.h) and [trampoline_tinygo_arm64.h](https://github.com/u-root/u-root/blob/main/pkg/boot/universalpayload/trampoline_tinygo_arm64.h). The behavior will diverge and it might be hard to debug in the future.

2025-01-06 10:48 UTC, leongross reviewed
Just as a reminder, since I am currently working on the tiyngo support; the current changes you proposed will only affect the non-tinygo builds, since you did not adjust the cgo implementations in [trampoline_tinygo_amd64.h](https://github.com/u-root/u-root/blob/main/pkg/boot/universalpayload/trampoline_tinygo_amd64.h) and [trampoline_tinygo_arm64.h](https://github.com/u-root/u-root/blob/main/pkg/boot/universalpayload/trampoline_tinygo_arm64.h). The behavior will diverge and it might be hard to debug in the future.

2025-01-06 20:06 UTC, 10000TB commented
We need all new changes to work for both tinygo, and non-tinygo builds. 

@AjanZhong  can you help adapt accordingly ?

2025-01-06 20:08 UTC, 10000TB requested changes
We need all new changes to work for both tinygo, and non-tinygo builds.

 @AjanZhong : can you help adapt accordingly ?

2025-01-07 01:42 UTC, AjanZhong commented
@leongross Hi Leon, would you mind help provide wiki on how to validate u-root with tinygo. Then I can help to update cgo implementation and validate it. Thanks.

2025-01-07 03:10 UTC, AjanZhong commented
I found this documentation for tinygo build, and will follow this doc to build and validate. https://github.com/u-root/u-root/blob/main/tools/tinygobb/README.md .

2025-01-07 03:58 UTC, AjanZhong commented
Hi all, I have tinygo installed, and tried to build/validate with tinygo build by this command:
u-root -tags tinygo -o $PWD/initramfs.linux_amd64.cpio -files "$UEFIPAYLOAD_PATH:/ext/upl" -uinitcmd="/bbin/kexec /ext/upl" cmds/core/{init,gosh,kexec}

However, get following error message:
11:52:50 INFO Skipping package github.com/u-root/u-root/cmds/core/gosh because build constraints exclude all Go files
11:52:50 INFO Skipping package github.com/u-root/u-root/cmds/core/kexec because build constraints exclude all Go files

According to record in https://github.com/u-root/u-root/blob/main/tools/tinygobb/README.md, kexec is not supported by tinygo now, and we have no way to validate cgo changes for tinygo.

So my suggestion is that, merge this PR first, update CGO implementation once kexec and gosh can be built with tinygo.

2025-01-07 07:10 UTC, AjanZhong commented
Also, I created a draft PR which is used to update cgo for trampoline code: https://github.com/u-root/u-root/pull/3266, not validated yet.

2025-01-07 18:00 UTC, rminnich approved these changes
This seems ok now that the other PR is in the queue for tinygo.

2025-01-08 02:26 UTC, AjanZhong commented
> This seems ok now that the other PR is in the queue for tinygo.

Thanks Ron Minnich.
@leongross Hi Leon, how about get this PR merged first, then then we can start to review PR (https://github.com/u-root/u-root/pull/3266) for tinygo implementation on trampoline code?

2025-01-08 09:53 UTC, leongross commented
> @leongross Hi Leon, would you mind help provide wiki on how to validate u-root with tinygo. Then I can help to update cgo implementation and validate it. Thanks.

One recent development is the creation of an integration test CI #3248 that builds each cmdlet individually, but no busybox itself. It is checked against a list of known good cmdlets that we know built, that are updated regularly.
Further, we do not run automated unit/integration tests for tinygo since we have not yet addressed some issues in the tinygo runtime.
So as of right now, there is no universal way to test if a subcommand built with tinygo works but to test it manually.

2025-01-08 09:55 UTC, leongross approved these changes
> This seems ok now that the other PR is in the queue for tinygo.

I agree. We addressed this issue and have it on our roadmap, so I see no reason to block this PR.

2025-01-09 15:14 UTC, leongross commented
As far as I can tell, the required changes to be compatible with tinygo were addressed in  https://github.com/u-root/u-root/pull/3266, so should we get this in?

2025-01-10 00:57 UTC, AjanZhong commented
> As far as I can tell, the required changes to be compatible with tinygo were addressed in #3266, so should we get this in?

My suggestion is to merge #3256 and #3266 step by step, it makes thing simple.
@10000TB  Would you mind help merge this PR, since it ready to merge now. Thanks.

2025-01-10 14:37 UTC, jensdrenhaus approved these changes
Seems ok from my side. 
This PR adds functionality that only takes effect on non-tinygo build. The tiny-go implementation will come with #3266. 
And most important: This PR does not break any existing tinygo existing functionality, as reported be the new CI step.
So @10000TB I also recommend merging this PR

2025-01-14 21:41 UTC, 10000TB approved these changes

2025-01-14 21:41 UTC, 10000TB commented
Thanks everyone.

2025-01-14 22:31 UTC, 10000TB commented
"@github-actions Tests / test (1.22.x, amd64, .) (pull_request) Failing after 11m". ------ It looks like one of the CI failed.

2025-01-15 01:33 UTC, AjanZhong commented
> "@github-actions Tests / test (1.22.x, amd64, .) (pull_request) Failing after 11m". ------ It looks like one of the CI failed.

vm test failure, let me check it.

2025-01-15 03:12 UTC, AjanZhong commented
> > "@github-actions Tests / test (1.22.x, amd64, .) (pull_request) Failing after 11m". ------ It looks like one of the CI failed.
> 
> vm test failure, let me check it.

This issue cannot be reproduced in local. I have rebased PR, and let us trigger CI to check.

2025-01-15 04:12 UTC, AjanZhong commented
> > > "@github-actions Tests / test (1.22.x, amd64, .) (pull_request) Failing after 11m". ------ It looks like one of the CI failed.
> > 
> > 
> > vm test failure, let me check it.
> 
> This issue cannot be reproduced in local. I have rebased PR, and let us trigger CI to check.

@10000TB GitHub CI check passed, would you mind help merge it again. Thanks.

2025-01-15 16:27 UTC, 10000TB approved these changes

2025-01-15 16:27 UTC, merged